USE mysql;
FLUSH PRIVILEGES ;
GRANT ALL ON *.* TO 'root'@'%' identified by 'root' WITH GRANT OPTION ;
GRANT ALL ON *.* TO 'root'@'localhost' identified by 'root' WITH GRANT OPTION ;
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('root');
DROP DATABASE IF EXISTS test ;
FLUSH PRIVILEGES ;
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER 'db_user'@'%' IDENTIFIED BY 'db_password';
GRANT ALL ON wordpress.* TO 'db_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
