apiVersion: v1
kind: Service
metadata:
 name: ftps
 annotations:
  metallb.universe.tf/allow-shared-ip: shared
spec:
 selector:
  app: ftps
 type: LoadBalancer
 ports:
  - port: 21
    name: ftp21
  - port: 20
    name: ftp20
  - port: 30000
    name: ftp30000
  - port: 30001
    name: ftp30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ftps
 template:
  metadata:
   labels:
    app: ftps
  spec:
   containers:
   - name: ftps
     image: ftps:latest
     imagePullPolicy: Never
